/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.Calendar;
import gui.TutorForm;

/**
 *
 * @author biancapokhrel
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TutorOrTuteeButtonConfirm = new javax.swing.JButton();
        CalendarButtonConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        TutorOrTuteeButtonConfirm.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 18)); // NOI18N
        TutorOrTuteeButtonConfirm.setText("Tutor/Tutee Form");
        TutorOrTuteeButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorOrTuteeButtonConfirmActionPerformed(evt);
            }
        });

        CalendarButtonConfirm.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 18)); // NOI18N
        CalendarButtonConfirm.setText("Calendar");
        CalendarButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalendarButtonConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(TutorOrTuteeButtonConfirm))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(CalendarButtonConfirm)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(TutorOrTuteeButtonConfirm)
                .addGap(37, 37, 37)
                .addComponent(CalendarButtonConfirm)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TutorOrTuteeButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorOrTuteeButtonConfirmActionPerformed
        // TODO add your handling code here:
        TutorForm tutorClicked = new TutorForm();
        tutorClicked.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TutorOrTuteeButtonConfirmActionPerformed

    private void CalendarButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalendarButtonConfirmActionPerformed
        // TODO add your handling code here:
        Calendar calendarClicked = new Calendar();
        calendarClicked.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CalendarButtonConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalendarButtonConfirm;
    private javax.swing.JButton TutorOrTuteeButtonConfirm;
    // End of variables declaration//GEN-END:variables
}
