/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author biancapokhrel
 */
public class TutorForm extends javax.swing.JFrame {

    /**
     * Creates new form TutorForm
     */
    public TutorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SubmitForm = new javax.swing.JButton();
        Monday = new javax.swing.JCheckBox();
        needTutor = new javax.swing.JCheckBox();
        beATutor1 = new javax.swing.JCheckBox();
        Wednesday = new javax.swing.JCheckBox();
        Tuesday = new javax.swing.JCheckBox();
        Thursday = new javax.swing.JCheckBox();
        Friday = new javax.swing.JCheckBox();
        AfterSchool = new javax.swing.JCheckBox();
        Period4 = new javax.swing.JCheckBox();
        Period2 = new javax.swing.JCheckBox();
        Period5 = new javax.swing.JCheckBox();
        Period3 = new javax.swing.JCheckBox();
        Period1 = new javax.swing.JCheckBox();
        Physics = new javax.swing.JCheckBox();
        Math = new javax.swing.JCheckBox();
        Biology = new javax.swing.JCheckBox();
        Chemistry = new javax.swing.JCheckBox();
        French = new javax.swing.JCheckBox();
        English = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Hiragino Mincho Pro", 0, 14)); // NOI18N
        jLabel1.setText("What days are you available?");

        jLabel2.setFont(new java.awt.Font("Hiragino Mincho Pro", 0, 14)); // NOI18N
        jLabel2.setText("I want:");

        jLabel3.setFont(new java.awt.Font("Hiragino Mincho Pro", 0, 14)); // NOI18N
        jLabel3.setText("What subjects do you need tutoring/would like to tutor in?");

        jLabel4.setFont(new java.awt.Font("Hiragino Mincho Pro", 0, 14)); // NOI18N
        jLabel4.setText("When are you available these days?");

        SubmitForm.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 18)); // NOI18N
        SubmitForm.setText("SUBMIT   ⇰ ");
        SubmitForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitFormActionPerformed(evt);
            }
        });

        Monday.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Monday.setText("Monday");
        Monday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MondayActionPerformed(evt);
            }
        });

        needTutor.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        needTutor.setText("To get a tutor");

        beATutor1.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        beATutor1.setText("To be a tutor");

        Wednesday.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Wednesday.setText("Wednesday");
        Wednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WednesdayActionPerformed(evt);
            }
        });

        Tuesday.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Tuesday.setText("Tuesday");
        Tuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesdayActionPerformed(evt);
            }
        });

        Thursday.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Thursday.setText("Thursday");
        Thursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThursdayActionPerformed(evt);
            }
        });

        Friday.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Friday.setText("Friday");
        Friday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FridayActionPerformed(evt);
            }
        });

        AfterSchool.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        AfterSchool.setText("After School");

        Period4.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Period4.setText("Period 4");

        Period2.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Period2.setText("Period 2");

        Period5.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Period5.setText("Period 5");

        Period3.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Period3.setText("Period 3");

        Period1.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Period1.setText("Period 1");

        Physics.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Physics.setText("Physics");
        Physics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhysicsActionPerformed(evt);
            }
        });

        Math.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Math.setText("Math");
        Math.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathActionPerformed(evt);
            }
        });

        Biology.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Biology.setText("Biology");
        Biology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiologyActionPerformed(evt);
            }
        });

        Chemistry.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        Chemistry.setText("Chemistry");
        Chemistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChemistryActionPerformed(evt);
            }
        });

        French.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        French.setText("French");
        French.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenchActionPerformed(evt);
            }
        });

        English.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        English.setText("English");
        English.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Tuesday)
                                        .addGap(18, 18, 18)
                                        .addComponent(Thursday))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Monday)
                                        .addGap(17, 17, 17)
                                        .addComponent(Wednesday)))
                                .addGap(18, 18, 18)
                                .addComponent(Friday))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(beATutor1)
                                .addGap(26, 26, 26)
                                .addComponent(needTutor))
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Period1)
                                .addGap(18, 18, 18)
                                .addComponent(Period3)
                                .addGap(18, 18, 18)
                                .addComponent(Period5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Period2)
                                .addGap(18, 18, 18)
                                .addComponent(Period4)
                                .addGap(18, 18, 18)
                                .addComponent(AfterSchool))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(English)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Physics))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(French)
                                        .addGap(18, 18, 18)
                                        .addComponent(Math)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Chemistry)
                                    .addComponent(Biology)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(SubmitForm)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(needTutor)
                    .addComponent(beATutor1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Monday)
                    .addComponent(Friday)
                    .addComponent(Wednesday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Thursday)
                    .addComponent(Tuesday))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Period1)
                    .addComponent(Period3)
                    .addComponent(Period5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Period2)
                    .addComponent(Period4)
                    .addComponent(AfterSchool))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chemistry)
                    .addComponent(Math)
                    .addComponent(French))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Biology)
                    .addComponent(Physics)
                    .addComponent(English))
                .addGap(23, 23, 23)
                .addComponent(SubmitForm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitFormActionPerformed
        // TODO add your handling code here:

        //if submission is ok:
        MainFrame formSubmitted = new MainFrame();
        formSubmitted.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SubmitFormActionPerformed

    private void FridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FridayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FridayActionPerformed

    private void MondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MondayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MondayActionPerformed

    private void TuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuesdayActionPerformed

    private void WednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WednesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WednesdayActionPerformed

    private void ThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThursdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThursdayActionPerformed

    private void MathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MathActionPerformed

    private void ChemistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChemistryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChemistryActionPerformed

    private void FrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FrenchActionPerformed

    private void EnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnglishActionPerformed

    private void PhysicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhysicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhysicsActionPerformed

    private void BiologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiologyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiologyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AfterSchool;
    private javax.swing.JCheckBox Biology;
    private javax.swing.JCheckBox Chemistry;
    private javax.swing.JCheckBox English;
    private javax.swing.JCheckBox French;
    private javax.swing.JCheckBox Friday;
    private javax.swing.JCheckBox Math;
    private javax.swing.JCheckBox Monday;
    private javax.swing.JCheckBox Period1;
    private javax.swing.JCheckBox Period2;
    private javax.swing.JCheckBox Period3;
    private javax.swing.JCheckBox Period4;
    private javax.swing.JCheckBox Period5;
    private javax.swing.JCheckBox Physics;
    private javax.swing.JButton SubmitForm;
    private javax.swing.JCheckBox Thursday;
    private javax.swing.JCheckBox Tuesday;
    private javax.swing.JCheckBox Wednesday;
    private javax.swing.JCheckBox beATutor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox needTutor;
    // End of variables declaration//GEN-END:variables
}
